# Cameron Bielstein, 1/22/15
# Toys Makefile

CXX = g++
CFLAGS = -Wall -std=c++11

# If DEBUG=1 in build command, allow debugging
# else, optimize
ifeq ($(DEBUG), 1)
    CFLAGS += -g -O0
else
    CFLAGS += -O2
endif

ifeq ($(VALGRIND), 1)
    TESTFLAGS += valgrind --leak-check=full
endif

ifeq ($(GDB), 1)
    TESTFLAGS += gdb --args
endif

.PHONY: all
all: $(OBJECTS) $(TEST_OBJECTS)

.PHONY: help
help:
	@echo "Use the following commands:\n\
           all: makes all files\n\
           clean: deletes all files generated by builds\n\
           DEBUG=1: builds with symbols and no optimization\n\
           VALGRIND=1: runs under valgrind\n\
           GDB=1: runs the under gdb\n"

.PHONY: FilePrinter
FilePrinter: FilePrinter/file_printer.cpp
	$(CXX) FilePrinter/file_printer.cpp -o FilePrinter/FilePrinter $(CFLAGS)
	$(GDB) $(VALGRIND) ./FilePrinter/FilePrinter FilePrinter/test.txt FilePrinter/test2.txt

.PHONY: clean
clean:
	rm FilePrinter/FilePrinter
